RussianFedora/rf-web

themes/rf-web/templates/header_helper.tmpl
=> Update links (http -> https mostly)

conf.py
=> Add legal and hosting info

conf.py
This sidebar requires more work. We need at least to include Fedora banner
and have a proper layout for it.
=> Temporary remove links sidebar

conf.py
=> Switch to http in site_url

conf.py, stories/skachat.rst
=> Updated download page

stories/skachat.rst
=> Updated RFRemix spins URLs.

content/kristian-høgsberg-перешел-из-intel-в-google.rst, content/wayland-в-chromeos.rst, posts/wayland-i-google.rst
=> Wayland и Google

posts/kernelorg-otkazyvaetsia-ot-ftp-serverov.rst
=> Kernel.org shuts down ftp

content/Че-там-у-systemd.rst, posts/proekty-storaged-i-udisks2-obiavili-o-sliianii.rst
=> Udisks and storaged merge

content/Слайды-с-выступления-Павла-Емельянова-на-devops-moscow-meetup.rst, content/Что-там-у-systemd.rst, posts/docker-v-production.rst
=> Docker in prod #2

posts/systemd-233.rst
=> systemd 233

posts/netflix-ne-rabotaet-v-firefox-v-fedora.rst
=> Netflix в Fedora

posts/v-systemd-vkliuchili-podderzhku-patcha-barmina.rst
=> Systemd rm -rf

posts/docker-pereimenovali-v-moby.rst
=> Docker renames to Moby

posts/docker-pereimenovali-v-moby.rst
=> More details

stories/skachat.rst
* Added RFRemix 26 download links.
* Removed RFRemix 24 download links.
=> RFRemix 26 download links

.gitignore, .travis.yml, conf.py, requirements.txt, utils/deploy.sh
* Установлен плагин `deploy_hooks`
* При вызове `nikola deploy` составляется список новых постов
* Твиттер хук настраивается через env vars и постит ссылки на новые посты
Конфигурация:
* Создать новое приложение на аккаунте https://apps.twitter.com/app/new
* На вкладке "Keys and Access Tokens" разрешить ему постить в этот аккаунт
* travis env set TWITTER_CONSUMER_KEY foo
* travis env set TWITTER_CONSUMER_SECRET bar
* travis env set TWITTER_OAUTH_TOKEN user_foo
* travis env set TWITTER_OAUTH_TOKEN_SECRET user_bar
Fixes #36
=> Autopost to Twitter

posts/novaia-obuchalka-po-selinux.rst
=> SELinux tutorial

content/Новости-fedora-legal.rst, posts/istekli-patenty-na-s3tc.rst, posts/novye-patentnye-obiazatelstva-ot-red-hat.rst
=> S3TC patents expired

posts/materialy-s-konferentsii-gstreamer-conference-2017-i-all-systems-go-2017.rst
=> Материалы с конференций GStreamer Conference 2017 и All Systems Go 2017

stories/skachat.rst
* Added RFRemix 27 download links.
* Updated other links.
* Added new LiveUSB manual link.
=> RFRemix 27 download links

content/Что-там-у-systemd.rst, posts/systemd-236.rst
=> systemd 236

posts/g729-kodek-teper-patentno-chist.rst
=> G.729 in Fedora

posts/alternative-channels.rst
=> Added alternative channels

posts/vyshel-rfremix-28.rst, stories/skachat.rst
* Replaced update command.
* Added RFR28 to download page.
=> Rfr28 fixes

posts/materialy-s-redhat-summit-2018.rst
=> Red Hat Summit 2018

stories/skachat.rst
Fixed link to Fedora Media Writer.
Closes #160.
=> Fixed link to Fedora Media Writer

stories/skachat.rst
Updated download links from 28.0 release to 28.1.
=> Updated download links from 28.0 release to 28.1

posts/microsoft-prisoedinilas-k-open-invention-network.rst
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
=> MS joins OIN

posts/mpeg-1-i-mpeg-2-patentno-chisty.rst
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
=> MPEG-1 and MPEG-2 freed

stories/skachat.rst
Added Fedora 32 download links.
=> Added Fedora 32 download links

posts/gnomy-pobedili-trollia.rst, posts/problemy-s-fedora-32.rst
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
=> Fedora 32 GCC issues

posts/izmeneniia-v-fedora-33.rst
Signed-off-by: Peter Lemenkov <lemenkov@gmail.com>
=> F-33 new features #2

stories/skachat.rst
Added Fedora 33 download links.
=> Added Fedora 33 download links

stories/skachat.rst
Added Fedora 34 download links.
=> Added Fedora 34 download links
